# Generated by Django 4.0.5 on 2022-07-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminName', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adminPassword', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'admin501',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('custEmail', models.CharField(max_length=30)),
                ('foodId', models.CharField(max_length=10)),
                ('foodName', models.CharField(max_length=30)),
                ('foodPrice', models.FloatField()),
                ('foodQuantity', models.CharField(max_length=10)),
                ('totalPrice', models.FloatField()),
            ],
            options={
                'db_table': 'cart501',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custName', models.CharField(max_length=30)),
                ('custEmail', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('custPassword', models.CharField(max_length=10)),
                ('custContact', models.CharField(max_length=10)),
                ('custAddress', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customer501',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=30)),
                ('foodType', models.CharField(max_length=30)),
                ('foodCategory', models.CharField(max_length=30)),
                ('foodPrice', models.FloatField(max_length=30)),
            ],
            options={
                'db_table': 'food501',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('custEmail', models.CharField(max_length=30)),
                ('orderDate', models.CharField(max_length=30)),
                ('totalBill', models.FloatField()),
            ],
            options={
                'db_table': 'order501',
            },
        ),
    ]
